// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCre5BqmmFik9toJqjiiC_5wlzMo2MIzsk',
    appId: '1:966955257104:web:91dc7394c2c4940d52e995',
    messagingSenderId: '966955257104',
    projectId: 'wedify-398b7',
    authDomain: 'wedify-398b7.firebaseapp.com',
    storageBucket: 'wedify-398b7.firebasestorage.app',
    measurementId: 'G-2JSG2D7J8Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKgmrt5ihLkPdXK6tpRXY5UBwJS3fRHLY',
    appId: '1:966955257104:android:6470e17195f601ac52e995',
    messagingSenderId: '966955257104',
    projectId: 'wedify-398b7',
    storageBucket: 'wedify-398b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3ZheOiBd-ZXCDCB_mVTP9Ca6bwe4h_VQ',
    appId: '1:966955257104:ios:1702841e84c55caf52e995',
    messagingSenderId: '966955257104',
    projectId: 'wedify-398b7',
    storageBucket: 'wedify-398b7.firebasestorage.app',
    iosBundleId: 'com.example.wedify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCre5BqmmFik9toJqjiiC_5wlzMo2MIzsk',
    appId: '1:966955257104:web:d8688e40f51d22ae52e995',
    messagingSenderId: '966955257104',
    projectId: 'wedify-398b7',
    authDomain: 'wedify-398b7.firebaseapp.com',
    storageBucket: 'wedify-398b7.firebasestorage.app',
    measurementId: 'G-N82EJEFFTC',
  );
}
